# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DIVESH KUMAR
email: divesh.kumar@yale.edu
description: > # this means to ignore newlines until "baseurl:"
The undertaking of a new action brings new strength. I credit the Jekyll community for this webpage's theme. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Divesh
github_username: LinkedIn


# Build settings
markdown: kramdown
